services:
  db:
    image: postgres:16
    container_name: soc_db
    environment:
      POSTGRES_USER: soc
      POSTGRES_PASSWORD: miko2003
      POSTGRES_DB: soc
    ports:
      - "5432:5432"
    volumes:
      - soc_data:/var/lib/postgresql/data

volumes:
  soc_data: